# Generated by Django 5.2.12 on 2026-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty_models', '0002_evaluation_needs_reeval'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='india_payable',
            field=models.BooleanField(default=False, help_text='True if payment_method is bank_transfer or crypto'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Crypto'), ('paypal', 'PayPal'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
